baseURL = '/'
languageCode = 'en-us'
title = 'The Mad House'

buildFuture = true
buildDrafts = false
pagination.pagerSize = 12

DefaultContentLanguage = 'en'
defaultContentLanguage = 'en'
pluralizelisttitles = 'false'

refLinksErrorLevel = 'WARNING'
refLinksNotFoundURL = '/'

timeout = 60000

rssLimit = 3

enableInlineShortcodes = true

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  page = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser.attribute]
    block = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'onesenterprise'
    tabWidth = 4

[permalinks]
  posts = '/:year/:month/:slugorfilename/'
  categories = '/:slug/'

[params]
  author = 'Kris De Decker'
  description = 'This is a solar-powered website, which means it sometimes goes offline'

[menu]
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 1
  [[menu.main]]
    identifier = 'ongoingprojects'
    name = 'On Going Projects'
    url = '/ongoing-projects/'
    weight = 2
  [[menu.main]]
    identifier = 'projectoutputs'
    name = 'Project Outputs'
    url = '/project-outputs/'
    weight = 3
  [[menu.main]]
    identifier = 'other'
    name = 'Other'
    url = '/other/'
    weight = 4
  [[menu.main]]
    identifier = 'archives'
    name = 'Archive'
    url = '/archives/'
    weight = 5


[taxonomies]
  author = 'authors'
  tag = 'tags'
  category = 'categories'
  translator = 'translators'
  lang = 'languages'

[related]
  includeNewer = true
  threshold = 80
  toLower = false
  [[related.indices]]
    name = 'tags'
    weight = 100
  [[related.indices]]
    name = 'lang'
    weight = 80
